# Generated by Django 6.0.3 on 2026-06-05 23:43

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_rename_unsubscribe_token_guineapig_auth_token_and_more'), ('api', '0003_alter_guineapigclaim_registered_at'), ('api', '0004_rename_product_preorderitem_product_listing_and_more'), ('api', '0005_alter_preorder_id'), ('api', '0006_rename_cancelled_guineapigclaim_canceled_and_more'), ('api', '0007_preorderwindow_notified_at')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('request_description', models.TextField()),
                ('requested_pickup_date', models.DateTimeField()),
                ('delivery_details', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('N', 'New Order'), ('R', 'In Review'), ('A', 'Accepted'), ('D', 'Declined'), ('C', 'Complete')], default='N')),
            ],
        ),
        migrations.CreateModel(
            name='GuineaPig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='GuineaPigDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('available_from', models.DateTimeField()),
                ('available_until', models.DateTimeField()),
                ('total_slots', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailingListSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Preorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pending Payment'), ('C', 'Confirmed'), ('F', 'Fulfilled'), ('X', 'Cancelled')], default='P')),
                ('stripe_payment_intent_id', models.CharField(blank=True, null=True, unique=True)),
                ('stripe_payment_status', models.CharField(blank=True, default='')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='PreorderListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PreorderWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('pickup_date', models.DateField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available', models.BooleanField()),
                ('image', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='PreorderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.preorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.preorderlisting')),
            ],
        ),
        migrations.AddField(
            model_name='preorderlisting',
            name='window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='api.preorderwindow'),
        ),
        migrations.AddField(
            model_name='preorder',
            name='window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.preorderwindow'),
        ),
        migrations.CreateModel(
            name='GuineaPigClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time', models.DateTimeField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('guinea_pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guineapig')),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guineapigdrop')),
            ],
            options={
                'unique_together': {('drop', 'guinea_pig')},
            },
        ),
        migrations.RenameField(
            model_name='guineapig',
            old_name='unsubscribe_token',
            new_name='auth_token',
        ),
        migrations.RenameField(
            model_name='mailinglistsubscriber',
            old_name='unsubscribe_token',
            new_name='auth_token',
        ),
        migrations.AddField(
            model_name='guineapigdrop',
            name='registration_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 27, 19, 42, 7, 461874, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preorderwindow',
            name='location',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preorderwindow',
            name='type',
            field=models.CharField(choices=[('R', 'Regular'), ('P', 'Pop-up')], default='R'),
        ),
        migrations.AlterField(
            model_name='guineapigclaim',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RenameField(
            model_name='preorderitem',
            old_name='product',
            new_name='product_listing',
        ),
        migrations.AddField(
            model_name='preorderlisting',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preorder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='guineapigclaim',
            old_name='cancelled',
            new_name='canceled',
        ),
        migrations.AlterField(
            model_name='preorder',
            name='status',
            field=models.CharField(choices=[('P', 'Pending Payment'), ('C', 'Confirmed'), ('F', 'Fulfilled'), ('X', 'Canceled')], default='P'),
        ),
        migrations.AddField(
            model_name='preorderwindow',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
