# Generated by Django 6.0.3 on 2026-03-27 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guineapig',
            old_name='unsubscribe_token',
            new_name='auth_token',
        ),
        migrations.RenameField(
            model_name='mailinglistsubscriber',
            old_name='unsubscribe_token',
            new_name='auth_token',
        ),
        migrations.AddField(
            model_name='guineapigdrop',
            name='registration_until',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 27, 19, 42, 7, 461874)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preorderwindow',
            name='location',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preorderwindow',
            name='type',
            field=models.CharField(choices=[('R', 'Regular'), ('P', 'Pop-up')], default='R'),
        ),
    ]
