# Generated by Django 6.0.3 on 2026-03-27 20:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_unsubscribe_token_guineapig_auth_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guineapigclaim',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
