# Generated by Django 6.0.3 on 2026-03-29 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_guineapigclaim_registered_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preorderitem',
            old_name='product',
            new_name='product_listing',
        ),
        migrations.AddField(
            model_name='preorderlisting',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
            preserve_default=False,
        ),
    ]
