# Generated by Django 6.0.3 on 2026-03-29 02:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_product_preorderitem_product_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
