# Generated by Django 6.0.3 on 2026-03-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_preorder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guineapigclaim',
            old_name='cancelled',
            new_name='canceled',
        ),
        migrations.AlterField(
            model_name='preorder',
            name='status',
            field=models.CharField(choices=[('P', 'Pending Payment'), ('C', 'Confirmed'), ('F', 'Fulfilled'), ('X', 'Canceled')], default='P'),
        ),
    ]
