# Generated by Django 6.0.3 on 2026-06-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_cancelled_guineapigclaim_canceled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorderwindow',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
